### ISSUE TITLE
Unable to refer to parameter types by a qualified name in function overload documentation reference

### ISSUE THREAD

**Issue by parzysty** [heremaps/gluecodium#786]
For following class in lime file:
```

class MapScene {    
    lambda LoadSceneCallback = (@Java("loadSceneError") MapError?) -> Void

    fun load_scene(
        map_scheme: MapScheme,
        callback: LoadSceneCallback?
    )

    fun load_scene(
        configuration_file: String,
        callback: LoadSceneCallback?
    )
}
```
when trying to refer in doc string to second overload with
```
[MapScene.load_scene(String,MapScene.LoadSceneCallback?)]
```
gluecodium fails with error:
```
Feb 23, 2021 11:21:31 AM com.here.gluecodium.common.LimeLogger log
SEVERE: File .../lime/MapScene.lime, element some.package..MapScene: Failed to resolve documentation reference [MapScene.load_scene(String,MapScene.LoadSceneCallback?)]
Feb 23, 2021 11:21:31 AM com.here.gluecodium.Gluecodium$Companion main
SEVERE: Running Gluecodium failed!
com.here.gluecodium.cli.GluecodiumExecutionException: Validation errors found, see log for details.
	at com.here.gluecodium.generator.cpp.CppGeneratorSuite.generate(CppGeneratorSuite.kt:123)
	at com.here.gluecodium.Gluecodium.executeGenerator$gluecodium(Gluecodium.kt:134)
	at com.here.gluecodium.Gluecodium.execute(Gluecodium.kt:111)
	at com.here.gluecodium.Gluecodium$Companion.main(Gluecodium.kt:314)
	at com.here.gluecodium.Gluecodium.main(Gluecodium.kt)
```

**Comment by parzysty** [comment]
Minimal file causing the issue
[MyClass.txt](https://github.com/heremaps/gluecodium/files/6028825/MyClass.txt)

**Comment by DanielKamkha** [comment]
The cause of the failure is a qualified parameter type name in `[MapScene.load_scene(String,MapScene.LoadSceneCallback?)]`. The same reference with a non-qualified name `[MapScene.load_scene(String,LoadSceneCallback?)]` works just fine.
